[package]
name = "hash-compress"
version = "0.1.0"
edition = "2021"
author = "Nebula<nebula@kora.gg>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
rayon = "1.5.2"